---
# tasks file for apigee-opdk-setup-bootstrap
- name: Update cache
  include_tasks: cache.yml

- name: Create installer path
  file:
    path: "{{ opdk_installer_path }}"
    state: directory
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"

- name: Install from a local web server or internet
  include_tasks: install-online.yml
  when: install_archive_mirror is not defined

- name: Install from a local archive file
  include_tasks: install-archive-mirror.yml
  when: install_archive_mirror is defined and install_archive_mirror | bool == True

- name: Validate that apigee-service exists
  stat:
    path: "{{ apigee_service }}"
  register: apigee_service

- name: Fail if apigee-service is not installed
  fail:
    msg: "Failing the playbook because apigee-service should be installed now and it was not installed"
  when: not apigee_service.stat.exists

- name: Install Apigee component with proxy - apigee-setup
  command: '/opt/apigee/apigee-service/bin/apigee-service apigee-setup install'
  when: (opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off') and apigee_service.stat.executable

