---
# tasks file for apigee-opdk-setup-bootstrap
- name: Download bootstrap
  bootstrap:
    dest_dir: '{{ opdk_installer_path }}'
    version: '{{ opdk_version }}'
    url: '{{ apigee_repo_url }}'
    user_name: '{{ apigee_repo_user }}'
    password: '{{ apigee_repo_password }}'
  register: results

- name: Bootstrap script exists
  stat:
    path: '{{ bootstrap_script }}'
  register: bootstrap_exists

- name: Cache bootstrap script state
  cache:
    key: bootstrap_script_exists
    value: '{{ bootstrap_exists.stat.exists }}'

- name: Fail the playbook if bootstrap fails to install
  fail:
    msg: 'Bootstrap installation failed, no point in letting this go further'
  when: not bootstrap_exists.stat.exists

- name: Force update apigee-service if update_apigee_service is set
  shell: "bash {{ bootstrap_script }} apigeeuser={{ apigee_repo_user }} apigeepassword='{{ apigee_repo_password }}' JAVA_FIX=C"
  when: update_apigee_service is defined and update_apigee_service | bool == True

- name: Install bootstrap from the provided apigee_repo_uri and apigee_repo_protocol
  shell: 'bash {{ bootstrap_script }} apigeeuser={{ apigee_repo_user }} apigeepassword={{ apigee_repo_password }} apigeerepohost={{ apigee_repo_uri }} apigeeprotocol={{ apigee_repo_protocol }}:// JAVA_FIX=C'
  args:
    creates: '{{ apigee_installation_home }}/apigee-service/bin/apigee-service'
  register: results
  env:
    JAVA_HOME: '{{ java_home }}'
  failed_when: results is defined and results.rc is defined and results.rc > 0 or results | failed
  when: apigee_stage is not defined

- name: Install bootstrap from development repositories
  shell: 'bash {{ bootstrap_script }} apigeeuser={{ apigee_repo_user }} apigeepassword={{ apigee_repo_password }} apigeestage={{ apigee_stage }} apigeerepohost={{ apigee_repo_uri }} apigeeprotocol={{ apigee_repo_protocol }}:// JAVA_FIX=C'
  args:
    creates: '{{ apigee_installation_home }}/apigee-service/bin/apigee-service'
  register: results
  env:
    JAVA_HOME: '{{ java_home }}'
  failed_when: results is defined and results.rc is defined and results.rc > 0 or results | failed
  when: apigee_stage is defined

