---
# tasks file for apigee-opdk-setup-bootstrap
- name: Create installer path
  file:
    path: "{{ opdk_installer_path }}"
    state: directory
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"

#- block:
#  - name: Find available epel repos
#    find:
#      pattern: "epel*"
#      path: /etc/yum.repos.d
#      recurse: yes
#      file_type: file
#    register: remove_repos
#
#  - name: Remove reference to epel if version is greater than 4.17.01
#    file:
#      path: "{{ item.path }}"
#      state: absent
#    with_items: "{{ remove_repos.files }}"
#
#  when: opdk_version | version_compare('4.17.01', '>=')

- include: install-online.yml
  when: archive_folder is not defined

- include: install-mirror.yml
  when: archive_folder is defined and not archive_folder == ''

- name: Validate that apigee-service exists
  stat:
    path: "{{ apigee_installation_home }}/apigee-service/bin/apigee-service"
  register: apigee_service

- name: Fail if apigee-service is not installed
  fail:
    msg: "Failing the playbook because apigee-service should be installed now and it was not installed"
  when: not apigee_service.stat.exists


